window_title: "Materials Cloud Tools: Transmission app"
page_title: "Transmission app"

#custom_css_files:
# input_data:
#    - custom.css
#  process_data:
#    - custom.css

#custom_js_files:
#  input_data:
#    - custom.js
#  process_data:
#    - custom.js

about_section_title: "About Transmission app"


templates:
  how_to_cite: "how_to_cite.html"
  about: "custom_about.html"
  select_content: "start_app.html"

additional_accordion_entries:
  - header: "Acknowledgements"
    template_page: ack.html
  - header: "Example picture"
    template_page: examp_pic.html

